app/models/anime.py
from datetime import datetime, timedelta
from sqlalchemy import desc
from sqlalchemy.ext.declarative import declared_attr
from app.exts import db


class Anime(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    title = db.Column(db.String(200), unique=True, nullable=False)
    folder_name = db.Column(db.String(200), unique=True, nullable=False)
    anime_image = db.Column(db.String(200), nullable=True)
    anime_days = db.Column(db.Integer, nullable=False)
    register_date = db.Column(
        db.DateTime, default=datetime.now, nullable=False
    )

    __tablename__ = 'anime'
    __table_args__ = {
        'extend_existing': True,
        'mysql_engine': 'InnoDB',
        'mysql_charset': 'utf8',
        'mysql_collate': 'utf8_general_ci'
    }

    @property
    def is_new(self):
        from app.models.anime_detail import AnimeDetail
        now = datetime.now().replace(hour=0, minute=0, second=0)
        anime_detail = AnimeDetail.query \
            .filter(AnimeDetail.anime_id == self.id) \
            .order_by(desc(AnimeDetail.id)) \
            .first()
        if anime_detail:
            return anime_detail.created_at >= now - timedelta(days=1)
        else:
            return False

    @declared_attr
    def anime_details(self):
        from app.models.anime_detail import AnimeDetail
        return db.relationship(AnimeDetail, order_by="asc(AnimeDetail.episode)")

app/models/anime_detail.py
from datetime import datetime
from app.exts import db


class AnimeDetail(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    anime_id = db.Column(db.Integer, db.ForeignKey('anime.id'), nullable=False)
    episode = db.Column(db.Integer, nullable=False)
    file = db.Column(db.String(200), nullable=False)
    file_vtt = db.Column(db.String(200), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.now)

    anime = db.relationship('Anime',)

    __tablename__ = 'anime_detail'
    __table_args__ = {
        'extend_existing': True,
        'mysql_engine': 'InnoDB',
        'mysql_charset': 'utf8',
        'mysql_collate': 'utf8_general_ci'
    }

app/__init__.py
# -*- coding: utf-8 -*-
import os
from flask import Flask, url_for, g, render_template
from app.views.anime import bp as anime_bp
from app.views.upload import bp as upload_bp
from app.exts import db, migrate
from app.models.anime import Anime


def create_app():
    app = Flask(__name__)
    app.register_blueprint(anime_bp)
    app.register_blueprint(upload_bp)
    app.config.from_object('app.config')

    db.init_app(app)
    migrate.init_app(app, db)

    @app.context_processor
    def override_url_for():
        return dict(url_for=dated_url_for)

    def dated_url_for(endpoint, **values):
        if endpoint == 'static':
            filename = values.get('filename', None)
            if filename:
                file_path = os.path.join(app.root_path,
                                         endpoint, filename)
                values['q'] = int(os.stat(file_path).st_mtime)
        return url_for(endpoint, **values)

    @app.route('/')
    def main():
        animes = Anime.query.all()
        return render_template('main.html', animes=animes)

    @app.route('/<int:anime_days>')
    def anime_days(anime_days):
        animes = Anime.query.filter(Anime.anime_days == anime_days).all()
        return render_template('main.html', animes=animes)

    return app

app/views/anime.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from app.models.anime_detail import AnimeDetail
from app.models.anime import Anime
from sqlalchemy import asc

bp = Blueprint('anime', __name__, url_prefix='/anime')


@bp.route('/detail/<int:anime_id>')
def anime_detail(anime_id):
    anime = Anime.query.filter(Anime.id == anime_id).first()
    rows = anime.anime_details
    title = anime.title
    return render_template('anime/detail.html', rows=rows, title=title)


@bp.route('/detail/<int:anime_id>/<int:episode>')
def show_anime(anime_id, episode):
    details = AnimeDetail.query \
        .filter(
        AnimeDetail.anime_id == anime_id,
        AnimeDetail.episode >= episode
    ) \
        .order_by(asc(AnimeDetail.episode)) \
        .limit(2) \
        .all()

    has_next_episode = len(details) > 1
    current_detail = details[0]

    return render_template('anime/watch.html',
                           has_next_episode=has_next_episode,
                           current_detail=current_detail)

app/views/upload.py
# -*- coding: utf-8 -*-
import os
from flask import Blueprint, render_template, request, current_app
from app.utils.change_vtt import change_vtt
from app.utils.smi2srt import convertSMI
from werkzeug.utils import secure_filename
from app.exts import db
from app.models.anime import Anime
from app.models.anime_detail import AnimeDetail
from sqlalchemy import desc

bp = Blueprint('upload', __name__)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in current_app.config[
               'ALLOWED_EXTENSTIONS']


def is_track_extenstion(filename):
    return '.smi' in filename


def create_new_anime(title, folder, img_name, anime_day):
    # insert db from anime

    anime = Anime(
        title=title,
        folder_name=folder,
        anime_image=img_name,
        anime_days=anime_day
    )
    db.session.add(anime)
    db.session.commit()


@bp.route('/upload')
def index():
    return render_template('upload/upload.html')


@bp.route('/uploaded', methods=['POST'])
def upload():
    uploaded_files = request.files.getlist("file[]")
    filenames = []

    # get form data
    title = request.form.get('title')
    folder = request.form.get('folder_name')
    image = request.files['image']
    anime_day = request.form.get('anime_day')

    img_name = (image.filename)
    image.save('{}/static/images/{}'.format(
        current_app.config['BASE_DIR'],
        img_name
    ))

    insert_anime = Anime.query.filter(Anime.folder_name == folder).all()

    # create new anime
    if not insert_anime:
        create_new_anime(title, folder, img_name, anime_day)

    # checking all upload files
    for file in uploaded_files:
        select_anime = Anime.query.filter(Anime.folder_name == folder).first()

        anime_idx = select_anime.id

        # check extenstions
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)

            # create new folder
            if not os.path.exists(
                    current_app.config['UPLOAD_FOLDER'] + folder):
                os.makedirs(current_app.config['UPLOAD_FOLDER'] + folder)

            insert_file_path = 'uploads/' + folder + '/' + filename
            file.save(
                os.path.join(current_app.config['UPLOAD_FOLDER'] + folder,
                             filename))

            episode = AnimeDetail.query.filter(
                AnimeDetail.anime_id == anime_idx).order_by(
                desc(AnimeDetail.episode)).first()
            print episode

            if is_track_extenstion(filename):
                convertSMI(filename, folder)

                # .smi file > .vtt file
                if '.smi' in filename:
                    filename = filename.split('.')
                    new_filename = filename[0] + '.vtt'
                    insert_file_path = '{}{}/{}'.format(
                        current_app.config['UPLOAD_FOLDER'],
                        folder,
                        new_filename
                    )
                    change_vtt(insert_file_path)

                    insert_vtt = AnimeDetail.query.filter(
                        AnimeDetail.anime_id == anime_idx,
                        AnimeDetail.episode == get_episode).first()

                    insert_vtt.file_vtt = 'uploads/' + folder + '/' + new_filename
                    db.session.commit()

            else:
                get_episode = episode.episode + 1 if episode is not None else 1

                insert_detail = AnimeDetail(
                    anime_id=anime_idx,
                    episode=get_episode,
                    file=insert_file_path
                )
                db.session.add(insert_detail)
                db.session.commit()


            filenames.append(filename)
        else:
            error_text = 'you can upload video extention'
            return render_template('upload/upload.html', error_text=error_text)
    return render_template('upload/uploaded.html', filenames=filenames)

app/templates/anime/detail.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
{% include "anime/nav.html" %}
<div class="container">
    <div class="collection">
        <h4

        >{{ title }}</h4>
        {% for row in rows %}
            <a class="collection-item"
               href="{{ url_for('anime.show_anime', anime_id=row.anime_id, episode=row.episode ) }}">{{ row.episode }}화</a>
        {% endfor %}
    </div>
</div>
</body>
</html>

app/templates/anime/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
<ul id="slide-out" class="side-nav fixed">
    <li>
        <div class="user-view" onclick="location.href='/';">
            <div class="background">
                <img src="/images/nav_main.png">
            </div>
        </div>
    </li>
    <!-- search bar -->
    <div class="nav-wrapper">
        <form>
            <div class="input-field">
                <input id="search" type="search" required>
                <label class="label-icon" for="search">
                    <i class="material-icons">search</i>
                </label>
                <i class="material-icons">close</i>
            </div>
        </form>
    </div>
    <li><div class="divider"></div></li>
    <li><a href="/0">MonDay</a></li>
    <li><a href="/1">Tuesday</a></li>
    <li><a href="/2">Wednesday</a></li>
    <li><a href="/3">Thursday</a></li>
    <li><a href="/4">Friday</a></li>
    <li><a href="/5">Saturday</a></li>
    <li><a href="/6">Sunday</a></li>
    <li><a href="/9">완 결</a></li>
</ul>
<a href="#" data-activates="slide-out" class="button-collapse">
    <i class="material-icons">menu</i>
</a>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script>
    $(".button-collapse").sideNav();
</script>
</body>
</html>

app/templates/anime/watch.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/style.css') }}">

</head>
<body>
{% include "anime/nav.html" %}
<div class="container">
    <video controls autoplay="autoplay">
        <source src="{{ url_for('static', filename=current_detail.file) }}"
                type="video/mp4">
        <source src="{{ url_for('static', filename=current_detail.file) }}"
                type="video/avi">
        {% if current_detail.file_vtt %}
            <track kind="subtitles" label="korean subtitles"
                   src="{{ url_for('static', filename=current_detail.file_vtt) }}"
                   srclang="ko" default>
        {% endif %}
    </video>
    {% if current_detail.episode > 1 %}
        <a class="waves-effect waves-light btn" href="{{ url_for('anime.show_anime', anime_id = current_detail.anime_id, episode = current_detail.episode - 1) }}"> 이전화 보기</a>
    {% endif %}
    <a class="waves-effect waves-light btn" href="{{ url_for('anime.anime_detail', anime_id = current_detail.anime_id) }}"> 목록 보기</a>
    {% if has_next_episode %}
        <a class="waves-effect waves-light btn" href="{{ url_for('anime.show_anime', anime_id = current_detail.anime_id, episode = current_detail.episode + 1) }}"> 다음화 보기</a>
    {% endif %}
</div>
</body>
</html>

app/templates/main.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% include "anime/nav.html" %}
    <div class="container">
        <div class="row">
            {% for anime in animes %}
                <div class="col s12 m7 l4 xl3 ">
                    <div class="post-module">
                        <!-- Thumbnail-->
                        <div class="thumbnail">
                            {% if anime.is_new %}
                                <div class="date">
                                    <div class="day">N</div>
                                </div>
                            {% endif %}
                            <a href="{{ url_for('anime.anime_detail', anime_id=anime.id) }}">
                                <img src="/static/images/{{ anime.anime_image }}" height=200px/>
                            </a>
                        </div>
                        <!-- Post Content-->
                        <div class="post-content">
                            <h3 class="title">{{ anime.title }}</h3>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

app/templates/upload/upload.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container">
    <div class="header">
        <h3 class="text-muted">파일 업로드</h3>
    </div>
    <hr/>
    <div>
        {{ error_text }}
        <form action="/uploaded" method="post" enctype="multipart/form-data">
            Title <input type="text" name="title"/><br/>
            Folder Name <input type="text" name="folder_name"/><br/>
            Image <input type="file" multiple="" name="image"
                         class="span3"/><br/>
            Video(s) <input type="file" multiple="" name="file[]"
                            class="span3"/><br/>
            select day
            <select name="anime_day">
                <option value="0">월</option>
                <option value="1">화</option>
                <option value="2">수</option>
                <option value="3">목</option>
                <option value="4">금</option>
                <option value="5">토</option>
                <option value="6">일</option>
                <option value="9">완결</option>
            </select><br/>
            <input type="submit" value="Upload" class="span2"/>
        </form>
    </div>
</div>
</body>
</html>

app/templates/upload/uploaded.html
<!DOCTYPE html>
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
	</head>
	<body>
        업로드 성공!
 	</body>
</html>

templates/detail.html
<!DOCTYPE html>
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
 	</head>
 	<body>
      {% include "nav.html" %}
      <div class="container">
        <div class="collection">
            <h4

            >{{ title }}</h4>
            {% for row in rows %}
                <a class="collection-item" href="{{url_for('show_anime', anime_id=row[1], episode=row[2] )}}">{{ row[2] }}화</a>
            {% endfor %}
        </div>
      </div>
 	</body>
</html>

templates/main.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% include "nav.html" %}
    <div class="container">
        <div class="row">
            {% for row in rows %}
                <div class="col s12 m7 l4 xl3 ">
                    <div class="post-module">
                        <!-- Thumbnail-->
                        <div class="thumbnail">
                            {% if row[6] %}
                                <div class="date">
                                    <div class="day">N</div>
                                </div>
                            {% endif %}
                            <a href="{{ url_for('anime_detail', anime_id=row[0]) }}">
                                <img src="images/{{ row[3] }}" height=200px/> {{ row[2] }}
                            </a>
                        </div>
                        <!-- Post Content-->
                        <div class="post-content">
                            <h3 class="title">{{ row[1] }}</h3>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/watch.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script>
        var link = document.location.href.split('?');
        var split_link = link[0].split("/");

        function next_page() {
            var next_episode;

            next_episode = split_link.pop();
            next_episode = parseInt(next_episode) + 1;
            split_link.push(next_episode.toString());
            split_link = split_link.join('/');
            window.location = split_link;
        }

        function detail_page() {
            split_link.pop();
            split_link = split_link.join('/');
            window.location = split_link;
        }

        function prev_page() {
            var prev_episode;

            prev_episode = split_link.pop();
            prev_episode = parseInt(prev_episode) - 1;
            split_link.push(prev_episode.toString());
            split_link = split_link.join('/');
            window.location = split_link;
        }


    </script>
</head>
<body>
{% include "nav.html" %}
<div class="container">
    <video controls autoplay="autoplay">
        <source src="{{ url_for('static', filename=ani_path) }}" type="video/mp4">
        <source src="{{ url_for('static', filename=ani_path) }}" type="video/avi">
        {% if vtt_path %}
            <track kind="subtitles" label="korean subtitles"
                   src="{{ url_for('static', filename=vtt_path) }}" srclang="ko" default>
        {% endif %}
    </video>
    {% if next_episode-1 > 1 %}
        <input type="button" value="이전" onClick="prev_page();">&nbsp;&nbsp;&nbsp;
    {% endif %}
    <input type="button" value="목록" onClick="detail_page();">&nbsp;&nbsp;&nbsp;
    {% if all_episode >= next_episode %}
        <input type="button" value="다음" onClick="next_page();">
    {% endif %}
</div>
</body>
</html>